# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% ../00_core.ipynb 3
import fastcore.test as ft
from nbdev import *

# %% ../00_core.ipynb 5
#| test case CoreTester unittest.TestCase

# %% ../00_core.ipynb 7
def test_addition():
    def addition(a,b): return a+b
    ft.test_eq(addition(1,2), 3)
    ft.test_eq(addition(-1,0), -1)
    ft.test_eq(addition(1,2), 3)
